name: Image Scan & SBOM (app path)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        run: |
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Generate Go SBOM (SPDX JSON) with Trivy
        run: |
          trivy fs --format spdx-json --output sbom-go.spdx.json .

      - name: Generate JS SBOM (SPDX JSON) with Trivy
        run: |
          trivy fs --include-dev-deps --format spdx-json --output sbom-js.spdx.json ./js

      - name: Build image (uses ./Dockerfile)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          load: true
          tags: gotrack:ci

      - name: Generate Image SBOM (SPDX JSON) with Trivy
        run: |
          trivy image --format spdx-json --output sbom-image.spdx.json gotrack:ci

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.sha }}
          path: |
            sbom-go.spdx.json
            sbom-js.spdx.json
            sbom-image.spdx.json
          if-no-files-found: error
          retention-days: 7
