name: SAST
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
  security-events: write

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install SAST tools
        run: |
          pip install --no-cache-dir "semgrep==1.*"
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Semgrep (OWASP + auto)
        run: semgrep --config p/owasp-top-ten --config auto --error --sarif -o semgrep.sarif || true

      - name: Gosec (Go SAST)
        run: gosec -fmt sarif -out gosec.sarif ./... || true

      - name: Staticcheck (Go static analysis)
        run: |
          staticcheck -f sarif ./... > staticcheck.sarif || true
          # Ensure SARIF file has valid structure
          if [ -f staticcheck.sarif ]; then
            if ! grep -q '"results"' staticcheck.sarif; then
              echo "Fixing staticcheck SARIF file - adding missing results array"
              # Add a minimal valid SARIF structure if it's missing
              python3 -c '
import json
import sys
try:
    with open("staticcheck.sarif", "r") as f:
        data = json.load(f)
    if "runs" in data:
        for run in data["runs"]:
            if "results" not in run:
                run["results"] = []
    with open("staticcheck.sarif", "w") as f:
        json.dump(data, f, indent=2)
except Exception as e:
    print(f"Error fixing SARIF: {e}")
    sys.exit(1)
'
            fi
          fi

      - name: List SARIF
        run: ls -lah *.sarif && head -n 20 gosec.sarif || true

      # Upload Semgrep first (sanity)
      - name: Upload SARIF (Semgrep)
        if: ${{ github.actor != 'nektos/act' && hashFiles('semgrep.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif
          wait-for-processing: true

      - name: Upload SARIF (Gosec)
        if: ${{ github.actor != 'nektos/act' && hashFiles('gosec.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gosec.sarif
          wait-for-processing: true

      - name: Upload SARIF (Staticcheck)
        if: ${{ github.actor != 'nektos/act' && hashFiles('staticcheck.sarif') != '' }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: staticcheck.sarif
          wait-for-processing: true

      - name: Save SARIF locally (act)
        if: ${{ github.actor == 'nektos/act' }}
        uses: actions/upload-artifact@v4
        with:
          name: sast-sarif
          path: |
            semgrep.sarif
            gosec.sarif
            staticcheck.sarif